[package]
name = "pg_blocking"
version = "0.1.0"
authors = ["Bedroom Builds"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
postgres = { version = "0.19.1", features=["with-chrono-0_4"]}
