[package]
name = "monte_carlo_pi"
version = "0.1.0"
authors = ["Bedroom Builds"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.0"
num_cpus = "1.13.0"
rand = "0.8.3"
